#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GeoTiles.Droid.Resource", IsApplication=true)]

namespace GeoTiles.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050018
			public const int btnQuad = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int btnStart = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int btnStop = 2131034113;
			
			// aapt resource value: 0x7f050017
			public const int btnTri = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int cells = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int editText2 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int imageView1 = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int imageView10 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int imageView11 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int imageView12 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int imageView13 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int imageView14 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int imageView15 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int imageView16 = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int imageView2 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageView3 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int imageView4 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int imageView5 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int imageView6 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int imageView7 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int imageView8 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageView9 = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int numSpeed = 2131034115;
			
			// aapt resource value: 0x7f050016
			public const int txtClue = 2131034134;
			
			// aapt resource value: 0x7f050004
			public const int txtScore = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int kite1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int kite2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int kite3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int kite4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int kite5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int kite6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int kite7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int kite8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int kite_template = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int parallelogram1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int parallelogram2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int parallelogram3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int parallelogram4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int parallelogram5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int parallelogram6 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int parallelogram7 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int parallelogram8 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rectangle1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int rectangle2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int rectangle3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int rectangle4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int rectangle5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int rectangle6 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int rectangle7 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rectangle8 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int rhombus1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rhombus2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rhombus3 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int rhombus4 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int rhombus5 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int rhombus6 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int rhombus7 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int rhombus8 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int square1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int square2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int square3 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int square4 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int square5 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int square6 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int square7 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int square8 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int trapezoid1 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int trapezoid2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int trapezoid3 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int trapezoid4 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int trapezoid5 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int trapezoid6 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int trapezoid7 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int trapezoid8 = 2130837553;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
