#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GeoTiles.Droid.Resource", IsApplication=true)]

namespace GeoTiles.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060021
			public const int btnBack = 2131099681;
			
			// aapt resource value: 0x7f06001d
			public const int btnFast = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int btnMode = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int btnNormal = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int btnQFast = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int btnQNormal = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int btnQSlow = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int btnQuad = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int btnScoreBack = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int btnShapeType = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int btnSlow = 2131099675;
			
			// aapt resource value: 0x7f06001f
			public const int btnSpeed = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btnStart = 2131099680;
			
			// aapt resource value: 0x7f060014
			public const int btnTri = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int cells = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int imageView10 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imageView11 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int imageView12 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageView13 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageView14 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int imageView15 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int imageView16 = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int imageView2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int imageView3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int imageView4 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int imageView5 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imageView6 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int imageView7 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int imageView8 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageView9 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int txtClue = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int txtLives = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int txtScore = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Scores = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Speed = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Summary = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int acute1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int acute2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int acute3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int acute4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int empty = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int equi1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int equi1a = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int equi2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int equi2a = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int equi3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int equi3a = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int equi4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int equi4a = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int i = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int iacute1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int iacute2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int iacute3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int iacute4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int iso = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int iso1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int iso2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int iso3 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int iso4 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int kite1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int kite2 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int kite3 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int kite4 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int kite5 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int kite6 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int kite7 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int kite8 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int kite_template = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int oiso1 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int oiso2 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int oiso3 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int oiso4 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int parallelogram1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int parallelogram2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int parallelogram3 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int parallelogram4 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int parallelogram5 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int parallelogram6 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int parallelogram7 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int parallelogram8 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int rectangle1 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int rectangle2 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int rectangle3 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int rectangle4 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int rectangle5 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int rectangle6 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int rectangle7 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int rectangle8 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int rhombus1 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int rhombus2 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int rhombus3 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int rhombus4 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int rhombus5 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int rhombus6 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int rhombus7 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int rhombus8 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int riso1 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int riso2 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int riso3 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int riso4 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rscalene1 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int rscalene2 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int rscalene3 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int rscalene4 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int sacute1 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int sacute2 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int sacute3 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int sacute4 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int sobtuse1 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int sobtuse2 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int sobtuse3 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int sobtuse4 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int square1 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int square2 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int square3 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int square4 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int square5 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int square6 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int square7 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int square8 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int trapezoid1 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int trapezoid2 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int trapezoid3 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int trapezoid4 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int trapezoid5 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int trapezoid6 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int trapezoid7 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int trapezoid8 = 2130837596;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int c = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int clap = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int correct = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int over = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int wrong = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int x = 2130968581;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
